"""add caching to referral code

Revision ID: 7f11eb90755a
Revises: 8d0f6d4b807a
Create Date: 2024-11-06 11:11:50.285860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f11eb90755a'
down_revision: Union[str, None] = '8d0f6d4b807a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
